envVars:
  - name: MS_SCHEDULED_PAYMENT_BASE_URL
    value: "https://ms-scheduled-payment.operations-and-execution/scheduled-payments/v1"
  - name: MS_SCHEDULED_PAYMENT_TIMEOUT
    value: "10000"

serviceAccount:
  create: false
