envVars:
  - name: MS_SINGLE_PAYMENTS_IMMEDIATE_PAYMENT_BASE_URL
    value: "https://api-dev.sfa.prodigio.tech/ms-scheduled-payment/single-payments/v1/scheduled-payment"
  - name: MS_SINGLE_PAYMENTS_IMMEDIATE_TIMEOUT
    value: "10000"

serviceAccount:
  create: false
